export const REQUEST_LIST = '[TASKS] REQUEST_LIST';
export const RESPONSE_LIST = '[TASKS] RESPONSE_LIST';
export const REQUEST_UPDATE = '[TASKS] REQUEST_UPDATE';
export const RESPONSE_UPDATE = '[TASKS] RESPONSE_UPDATE';
export const REQUEST_CREATE = '[TASKS] REQUEST_CREATE';
export const RESPONSE_CREATE = '[TASKS] RESPONSE_CREATE';
export const REQUEST_DELETE = '[TASKS] REQUEST_DELETE';
export const RESPONSE_DELETE = '[TASKS] RESPONSE_DELETE';
